### ISSUE TITLE
url, forkOf, and createdBy

### ISSUE THREAD

**Issue by pfrazee** [datprotocol/dat.json#6]
These are some attributes I use in Beaker. Add them? (If yes I can PR with a description)

 - `url`: the URL of the dat
 - `forkOf`: the URL of the dat which the current dat is a fork of. Can be an array, which indicates multiple forks, with the first entry being the original, and the last entry being the most recently forked-from.
 - `createdBy`: an object `{ url: String, title: String }` which indicates the application that created the dat. Title is optional.

**Comment by pfrazee** [comment]
Actually let's say `forkOf` must be an array of strings.

**Comment by karissa** [comment]
Why would there be multiple forks?
Do we want to include other kinds of metadata in a fork? Is just a string enough or would you want a copy of the fork's dat.json in there?

**Comment by pfrazee** [comment]
It's to indicate the lineage. If you fork a fork, there'd be 2 items in there.

```
forkOf: [grandparent-url (the original), parent-url]
```

If you forked that third fork, you'd get 3 items:

```
forkOf: [great-grandparent-url (the original), grandparent-url, parent-url]
```

I'm not entirely sure we *need* to include the lineage. We could just have the parent, and that would form the bare-minimum knowledge to traverse the graph, assuming all of the ancestors are still available.

As for extra metadata, that's a good question. What are the pros/cons?

**Comment by juliangruber** [comment]
Another advantage to only keeping the `forkOf` parent is that in distributed systems establishing linearity can sometimes be hard

**Comment by juliangruber** [comment]
> url: the URL of the dat

can you give an example?

> createdBy: an object { url: String, title: String } which indicates the application that created the dat. Title is optional.

I feel like this could be very optional, isn't it like adding the name of your editor to the source code?

**Comment by pfrazee** [comment]
> Another advantage to only keeping the forkOf parent is that in distributed systems establishing linearity can sometimes be hard

Yes though this is a pretty straight-forward mechanism: each time you make a fork, you append the url of the dat you're forking. It could be a *lie*, but otherwise it should work.

>> url: the URL of the dat

>can you give an example?

So, this field is the dat's own URL. I use it for bkr; it lets me identify which dat is in a directory.

>> createdBy: an object { url: String, title: String } which indicates the application that created the dat. Title is optional.

> I feel like this could be very optional, isn't it like adding the name of your editor to the source code?

Yeah. I use it for two reasons:

 1. It's useful in beaker's dat listing to help you identify a dat. "Oh that's the dat I made with the /log reader."
 2. It's nice for discovering an app that is capable of interacting with a dat, if it's a data dat.

**Comment by e-e-e** [comment]
+1 to forkOf having an array of strings. We are looking at using dat’s for structured collections of books and have been thinking through similar questions. Having multiple ancestors means that you can reconstruct lineage if one of the parents is offline.

**Comment by millette** [comment]
forkOf and createdBy are now deprecated in [beaker](https://github.com/beakerbrowser/beaker/pull/598).

**Comment by pfrazee** [comment]
Oh yeah, let's close this for now. The problem was that we were getting surprise information leaks, that made people uncomfortable. We've got to think through that and then maybe we can re-propose these.
