### ISSUE TITLE
move to datprotocol organization

### ISSUE THREAD

**Issue by karissa** [datprotocol/dat.json#9]
Can we move this to either github.com/datprotocol or github.com/datproject?

woot!

**Comment by pfrazee** [comment]
I'd suggest datprotocol

**Comment by juliangruber** [comment]
Yeah for sure let's move this to an org.

@pfrazee can you explain the difference between the two?

**Comment by pfrazee** [comment]
@juliangruber The datprotocol org is for protocol-level concerns, and for all apps that use Dat (Beaker included). The datproject org is for data science repositories.

**Comment by juliangruber** [comment]
<img width="482" alt="screen shot 2017-01-19 at 17 25 16" src="https://cloud.githubusercontent.com/assets/10247/22115158/4951d962-de6c-11e6-9258-235a668d5475.png">

**Comment by pfrazee** [comment]
Oh let me invite you, sorry

**Comment by juliangruber** [comment]
done!
